# Generated by Django 2.2.7 on 2019-11-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('domain_name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('item_domain', models.CharField(max_length=16)),
                ('item_name', models.CharField(max_length=255)),
                ('item_price', models.CharField(max_length=16)),
                ('item_image', models.CharField(max_length=255)),
            ],
        ),
    ]
