# Generated by Django 2.2.7 on 2019-11-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('domain_name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('tag_domain', models.CharField(max_length=16)),
                ('tag_name', models.CharField(max_length=255)),
                ('tag_price', models.CharField(max_length=16)),
                ('tag_image', models.CharField(max_length=255)),
            ],
        ),
    ]
