# Generated by Django 2.2.7 on 2019-12-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_price',
            field=models.CharField(max_length=255),
        ),
    ]
