# Generated by Django 3.0 on 2019-12-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserer', '0002_auto_20191203_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTag',
            fields=[
                ('domain_name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('tag_pagenum', models.CharField(max_length=255)),
                ('tag_review', models.CharField(max_length=255)),
            ],
        ),
    ]
