# Generated by Django 3.0 on 2019-12-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserer', '0003_rtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtag',
            name='tag_review',
            field=models.CharField(max_length=1024),
        ),
    ]
