# Generated by Django 3.0 on 2019-12-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserer', '0004_auto_20191207_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtag',
            name='tag_pagenum',
            field=models.CharField(max_length=1024),
        ),
    ]
