# Generated by Django 2.2.7 on 2019-11-28 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=1024)),
                ('user_email', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_url', models.CharField(max_length=1024)),
                ('item_domain', models.CharField(max_length=16)),
                ('item_name', models.CharField(max_length=1024)),
                ('item_price', models.CharField(max_length=1024)),
                ('item_image', models.CharField(max_length=1024)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticator.User')),
            ],
        ),
    ]
