# Generated by Django 2.2.7 on 2019-11-28 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_cart_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('item_url', models.CharField(max_length=1024)),
                ('item_domain', models.CharField(max_length=16)),
                ('item_name', models.CharField(max_length=1024)),
                ('item_price', models.CharField(max_length=1024)),
                ('item_image', models.CharField(max_length=1024)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticator.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart_items',
        ),
    ]
